import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/components/Providers/Providers";

export const metadata: Metadata = {
  title: "Trello Clone",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className="bg-ned-main-bg text-white">
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
